#!/bin/bash

EXIT=0

readonly BINARIES=(bash make pandoc rsync inkscape sed convert ssh ./postproc ./mkfavicons) 

check_dep()
{
  local c=$1
  echo -n "$c "
  if ! type "$c" &>/dev/null; then
    echo -e "\\033[1;31mmissing\033[0m"
    return 1
  else
    echo -e "\\033[1;32mfound\033[0m"
    return 0
  fi
}

{
  echo 'Command'
  echo '-------'

  for dep in ${BINARIES[@]}; do
    check_dep "$dep" || EXIT=1
  done | sort | sed 's^./^^'

} | column -t

exit $EXIT

