#!/usr/bin/env python3

import sys
import csv
from datetime import datetime

def main():
    FUNDS=0.0
    DONORT="##Donors\n|Date|Name|US$|\n|:--|:--|:--|\n"
    STATUST="""
## Funding Status

As of: {}

|                               | US$       |
|:------------------------------|:----------|
| **Yearly funding goals**      |           |
| Operating expenses            | 400 p.a.  |
| Reserve (1.5a)                | 600       |""".format(datetime.now().strftime("%Y-%m-%d"))
    GOALS={
            2016:1000,
            2017:400,
            2018:400 }
    with open(sys.argv[1], "r", encoding='ISO-8859-15') as FILE:
        d = csv.reader(FILE)
        next(d, None)
        for r in d:
            if "Received" in r[4]:
                t = datetime.strptime(r[0], "%m/%d/%Y")
                n = ".".join([ w[0] for w in r[3].split(" ") ]) + "."
                m = float(r[7])
                FUNDS+=m
                DONORT+="|{}|{}|{:.2f}|\n".format(t.strftime("%Y-%m-%d"), n, m)
        for y in GOALS:
            FUNDS-=GOALS[y]
            if abs(FUNDS)>GOALS[y]:
                break
            STATUST+="""|**{} funding goal**|**{}**|
|Shortfall|{:.2f}|\n""".format(y, GOALS[y],  0.0 if FUNDS>=0 else abs(FUNDS))
        print(STATUST)
        print(DONORT)
    return 0

if __name__ == "__main__":
    sys.exit(main())
