#!/usr/bin/env python3

import json
import yaml
import sys

BASE_URL ="https://www.bunsenlabs.org/img/frontpage-gallery"

def add_link(i):
    infix = i['base'] if 'base' in i else i['author']
    i['url'] = "{}/{}.jpg".format(BASE_URL,infix)
    i.pop('base', 0)
    i['thumbnail_url'] = "{}/thumbs/{}.thumb.jpg".format(BASE_URL, infix)
    return i

with open(sys.argv[1], "r") as IN:
    data = yaml.load(IN)['gallery']

data = [ add_link(e) for e in data ]

with open(sys.argv[2], "w") as OUT:
    json.dump(data, OUT, indent=2)
