#!/bin/bash

readonly INFILE=$1
readonly OUTDIR=$(dirname "$1");
readonly GENFILE=$2

shift 2

{ 
  for size in "$@"; do

    printf "\t%03dpx favicon ... " $size >&2
    #rsvg-convert -f png -a -w $size "$INFILE" > "${OUTDIR}/favicon${size}.png"
    #convert "$INFILE" -density 500 -resize ${size}x${size}  "$OUTDIR/favicon${size}.png"
    inkscape -h $size -w $size -C -e "$OUTDIR/favicon${size}.png" "$INFILE" &>/dev/null
    echo "done." >&2

    echo "<link rel='icon' href='img/favicon${size}.png' sizes='${size}x${size}'>"

  done
} > "$GENFILE"
