#!/usr/bin/env python3

from bs4 import BeautifulSoup
import sys
import os

def cell(imgurl, thumburl, alttext):
    return """<td style="text-align:center;"><a href="{}" title="{}"><img style="width:128px" src="{}" alt="{}"></a></td>""".format(imgurl, alttext, thumburl, alttext)

def main():
    if len(sys.argv) != 2 or not os.path.isfile(sys.argv[1]):
        return 1
    cells = []
    with open(sys.argv[1], "r") as FILE:
        soup = BeautifulSoup(FILE, "html.parser")
        for link in soup.find_all("a"):
            imgurl = link.attrs["href"]
            imgtext = link.find("img").attrs["alt"][2:][:-2]
            thumb = link.find("img").attrs["data-src"]
            cells.append(cell(imgurl, thumb, imgtext))
    print("""<table class="plain">""")
    for triplet in zip(*[iter(cells)]*4):
        print("<tr>", "".join(triplet), "</tr>")
    print("</table>")

if __name__ == "__main__":
    sys.exit(main())


