#!/usr/bin/env python3

from bs4 import BeautifulSoup
import sys
import os

def main():
    if len(sys.argv) != 2 or not os.path.isfile(sys.argv[1]):
        return 1
    with open(sys.argv[1], "r") as FILE:
        soup = BeautifulSoup(FILE, "html.parser")
        print("<ul>")
        for link in soup.find_all("a"):
            imgurl = link.attrs["href"]
            imgtext = link.find("img").attrs["alt"][2:][:-2]
            print('<li><a href="{}" title="{}">{}</a></li>'.format(imgurl,
                imgtext, imgtext))
        print("</ul>")

if __name__ == "__main__":
    sys.exit(main())


