#!/usr/bin/env python3

import sys
from yaml import load, dump
try:
    from yaml import CLoader as Loader, CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper

def entry(stem, alt):
    return """        <a href="img/frontpage-gallery/{}.jpg" title="Screenshot by {}" target="_blank">\
<img alt="[ Screenshot by {} ]" data-src="img/frontpage-gallery/thumbs/{}.thumb.jpg"></a>""".format(stem, alt, alt, stem)

if __name__ == "__main__":
    print("""<div class="sliderbox" style="display:none">
    <div id="slider">""")
    with open(sys.argv[1], "r") as FILE:
        for img in load(FILE)['gallery']:
            print(entry(img['base'] if 'base' in img else img['author'], img['author']))
    print("""    </div>
</div>""")
