#!/usr/bin/env python3

from django.utils import feedgenerator as fg
from bs4 import BeautifulSoup as bs
import sys
import os

if __name__ == "__main__":
    DESTDIR = sys.argv[1]
    feedhead = [
            "BunsenLabs Linux",
            "https://www.bunsenlabs.org",
            "BunsenLabs Linux is a distribution offering a light-weight and easily customizable Openbox desktop" ]
    atom = fg.Atom1Feed(*feedhead)
    rss = fg.Rss201rev2Feed(*feedhead)
    for root, dirs, files in os.walk(DESTDIR):
        if root != DESTDIR:
            break
        for f in sorted([ DESTDIR + '/' + f for f in files if f.endswith(".html") ]):
            with open(f, "r") as FILE:
                soup = bs(FILE, "html.parser")
                title = soup.find("title").text
                descr = soup.find("meta", {"name":"description"})["content"]
                atom.add_item(title, "https://www.bunsenlabs.org/" + f.split("/")[-1], descr)
                rss.add_item(title, "https://www.bunsenlabs.org/" + f.split("/")[-1], descr)
    with open(sys.argv[2], "w") as FILE:
        atom.write(FILE, "utf-8")
    with open(sys.argv[3], "w") as FILE:
        rss.write(FILE, "utf-8")
