#!/usr/bin/env python3

from argparse import ArgumentParser
from jinja2 import Environment, DictLoader
import sys
import yaml

if __name__ == '__main__':
    ap = ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True)
    ap.add_argument("--variables", required=True)
    ap = ap.parse_args()

    with open(ap.input, "r") as FILE:
        env = Environment(loader = DictLoader({ ap.input:FILE.read() }))
        tpl = env.get_template(ap.input)

    with open(ap.variables, "r") as FILE:
        vars = yaml.load(FILE)

    with open(ap.output, "w") as FILE:
        FILE.write(tpl.render(vars))
