#!/usr/bin/env python3
import feedparser
import sys
import pprint

def head(s, sep):
  return s.split(sep)[0]

if __name__=="__main__":
  feed = feedparser.parse("https://www.bunsenlabs.org/feed/news/atom")
  lbuf = ["""<div class="news"><noscript>"""]
  for e in feed.entries:
    link = head(e['link'], '&')
    date = head(e['updated'], 'T')
    title = e['title']
    text = e['summary']
    lbuf.append(f"""
<div class="news-section">
  <h2 class="news-heading"><span class="news-updated">{date}</span><a href="{link}">{title}</a></h2>
</div>""")
  lbuf.append("""<h2 class="news-archive"><a href="https://forums.bunsenlabs.org/viewforum.php?id=12">Older entries…</a></h2></noscript></div>""")
  with open(sys.argv[1],"w") as FILE:
    FILE.write("\n".join(lbuf))
