#!/usr/bin/env python3
import feedparser
import sys
import pprint

def head(s, sep):
  return s.split(sep)[0]

if __name__=="__main__":
  feed = feedparser.parse("https://forums.bunsenlabs.org/extern.php?action=feed&fid=12&type=atom")
  lbuf = ["""<ul class="news">"""]
  for e in feed.entries:
    link = head(e['link'], '&')
    date = head(e['updated'], 'T')
    title = e['title']
    text = e['summary']
    lbuf.append(f"""
<h2 class="news-heading"><span class="news-updated">{date}</span><a href="{link}">{title}</a></h2>
""")
  lbuf.append("</ul>")
  with open(sys.argv[1],"w") as FILE:
    FILE.write("\n".join(lbuf))
